

services:
  web:
    build: 
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: esschert_web
    command: ["bash", "-c", "/app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  celery:
    build: 
      context: .
      dockerfile: docker/celery/Dockerfile
    container_name: esschert_celery
    command: celery -A inriver_qr worker --loglevel=INFO
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  redis:
    image: redis:7
    container_name: esschert_redis
    ports:
      - "6379:6379"
