
services:
  web:
    build: 
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: inriver_web
    command: ["sh", "/app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: inriver_qr.settings
      DB_NAME: esschertqr
      DB_USER: root
      DB_PASSWORD: MysqlQR2025
      DB_HOST: host.docker.internal
      DB_PORT: 3306
    depends_on:
      - redis

  celery:
    build: 
      context: .
      dockerfile: docker/celery/Dockerfile
    container_name: inriver_celery
    command: celery -A inriver_qr worker --loglevel=INFO
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: inriver_qr.settings
      DB_NAME: esschertqr
      DB_USER: root
      DB_PASSWORD: MysqlQR2025
      DB_HOST: host.docker.internal
      DB_PORT: 3306
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: inriver_redis
    ports:
      - "6379:6379"
